server:
  port: 8313

spring:
  application:
    name: ACCOUNT-SERVICE
    

  datasource:
    url: jdbc:h2:mem:microservices
    driverClassName: org.h2.Driver
    username: root
    password: root

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show-sql: true 

  h2:
    console:
      enabled: true
      

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
